// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rippleapi/rippleapi.proto

package rippleapi

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EnumTransactionType int32

const (
	TX_ACCOUNT_SET            EnumTransactionType = 0
	TX_ACCOUNT_DELETE         EnumTransactionType = 1
	TX_CHECK_CANCEL           EnumTransactionType = 2
	TX_CHECK_CASH             EnumTransactionType = 3
	TX_CHECK_CREATE           EnumTransactionType = 4
	TX_DEPOSIT_PREAUTH        EnumTransactionType = 5
	TX_ESCROW_CANCEL          EnumTransactionType = 6
	TX_ESCROW_CREATE          EnumTransactionType = 7
	TX_ESCROW_FINISH          EnumTransactionType = 8
	TX_OFFER_CANCEL           EnumTransactionType = 9
	TX_OFFER_CREATE           EnumTransactionType = 10
	TX_PAYMENT                EnumTransactionType = 11
	TX_PAYMENT_CHANNEL_CLAIM  EnumTransactionType = 12
	TX_PAYMENT_CHANNEL_CREATE EnumTransactionType = 13
	TX_PAYMENT_CHANNEL_FUND   EnumTransactionType = 14
	TX_SET_REGULAR_KEY        EnumTransactionType = 15
	TX_SINGER_LIST_SET        EnumTransactionType = 16
	TX_TRUST_SET              EnumTransactionType = 17
)

var EnumTransactionType_name = map[int32]string{
	0:  "TX_ACCOUNT_SET",
	1:  "TX_ACCOUNT_DELETE",
	2:  "TX_CHECK_CANCEL",
	3:  "TX_CHECK_CASH",
	4:  "TX_CHECK_CREATE",
	5:  "TX_DEPOSIT_PREAUTH",
	6:  "TX_ESCROW_CANCEL",
	7:  "TX_ESCROW_CREATE",
	8:  "TX_ESCROW_FINISH",
	9:  "TX_OFFER_CANCEL",
	10: "TX_OFFER_CREATE",
	11: "TX_PAYMENT",
	12: "TX_PAYMENT_CHANNEL_CLAIM",
	13: "TX_PAYMENT_CHANNEL_CREATE",
	14: "TX_PAYMENT_CHANNEL_FUND",
	15: "TX_SET_REGULAR_KEY",
	16: "TX_SINGER_LIST_SET",
	17: "TX_TRUST_SET",
}

var EnumTransactionType_value = map[string]int32{
	"TX_ACCOUNT_SET":            0,
	"TX_ACCOUNT_DELETE":         1,
	"TX_CHECK_CANCEL":           2,
	"TX_CHECK_CASH":             3,
	"TX_CHECK_CREATE":           4,
	"TX_DEPOSIT_PREAUTH":        5,
	"TX_ESCROW_CANCEL":          6,
	"TX_ESCROW_CREATE":          7,
	"TX_ESCROW_FINISH":          8,
	"TX_OFFER_CANCEL":           9,
	"TX_OFFER_CREATE":           10,
	"TX_PAYMENT":                11,
	"TX_PAYMENT_CHANNEL_CLAIM":  12,
	"TX_PAYMENT_CHANNEL_CREATE": 13,
	"TX_PAYMENT_CHANNEL_FUND":   14,
	"TX_SET_REGULAR_KEY":        15,
	"TX_SINGER_LIST_SET":        16,
	"TX_TRUST_SET":              17,
}

func (EnumTransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_294224101de536c3, []int{0}
}

type Instructions struct {
	Fee                    string `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	MaxFee                 string `protobuf:"bytes,2,opt,name=maxFee,proto3" json:"maxFee,omitempty"`
	MaxLedgerVersion       uint32 `protobuf:"varint,3,opt,name=maxLedgerVersion,proto3" json:"maxLedgerVersion,omitempty"`
	MaxLedgerVersionOffset uint32 `protobuf:"varint,4,opt,name=maxLedgerVersionOffset,proto3" json:"maxLedgerVersionOffset,omitempty"`
	Sequence               uint32 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SignersCount           uint32 `protobuf:"varint,6,opt,name=signersCount,proto3" json:"signersCount,omitempty"`
}

func (m *Instructions) Reset()      { *m = Instructions{} }
func (*Instructions) ProtoMessage() {}
func (*Instructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_294224101de536c3, []int{0}
}
func (m *Instructions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Instructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Instructions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Instructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instructions.Merge(m, src)
}
func (m *Instructions) XXX_Size() int {
	return m.Size()
}
func (m *Instructions) XXX_DiscardUnknown() {
	xxx_messageInfo_Instructions.DiscardUnknown(m)
}

var xxx_messageInfo_Instructions proto.InternalMessageInfo

func (m *Instructions) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *Instructions) GetMaxFee() string {
	if m != nil {
		return m.MaxFee
	}
	return ""
}

func (m *Instructions) GetMaxLedgerVersion() uint32 {
	if m != nil {
		return m.MaxLedgerVersion
	}
	return 0
}

func (m *Instructions) GetMaxLedgerVersionOffset() uint32 {
	if m != nil {
		return m.MaxLedgerVersionOffset
	}
	return 0
}

func (m *Instructions) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Instructions) GetSignersCount() uint32 {
	if m != nil {
		return m.SignersCount
	}
	return 0
}

type RequestPrepareTransaction struct {
	TxType        EnumTransactionType `protobuf:"varint,1,opt,name=tx_type,json=txType,proto3,enum=rippleapi.EnumTransactionType" json:"tx_type,omitempty"`
	SenderAccount string              `protobuf:"bytes,2,opt,name=senderAccount,proto3" json:"senderAccount,omitempty"`
	Amount        float64             `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	//float amount = 3;
	ReceiverAccount string        `protobuf:"bytes,4,opt,name=receiverAccount,proto3" json:"receiverAccount,omitempty"`
	Instructions    *Instructions `protobuf:"bytes,5,opt,name=instructions,proto3" json:"instructions,omitempty"`
}

func (m *RequestPrepareTransaction) Reset()      { *m = RequestPrepareTransaction{} }
func (*RequestPrepareTransaction) ProtoMessage() {}
func (*RequestPrepareTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_294224101de536c3, []int{1}
}
func (m *RequestPrepareTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestPrepareTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestPrepareTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestPrepareTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPrepareTransaction.Merge(m, src)
}
func (m *RequestPrepareTransaction) XXX_Size() int {
	return m.Size()
}
func (m *RequestPrepareTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPrepareTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPrepareTransaction proto.InternalMessageInfo

func (m *RequestPrepareTransaction) GetTxType() EnumTransactionType {
	if m != nil {
		return m.TxType
	}
	return TX_ACCOUNT_SET
}

func (m *RequestPrepareTransaction) GetSenderAccount() string {
	if m != nil {
		return m.SenderAccount
	}
	return ""
}

func (m *RequestPrepareTransaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RequestPrepareTransaction) GetReceiverAccount() string {
	if m != nil {
		return m.ReceiverAccount
	}
	return ""
}

func (m *RequestPrepareTransaction) GetInstructions() *Instructions {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type ResponsePrepareTransaction struct {
	TxJSON       string        `protobuf:"bytes,1,opt,name=txJSON,proto3" json:"txJSON,omitempty"`
	Instructions *Instructions `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
}

func (m *ResponsePrepareTransaction) Reset()      { *m = ResponsePrepareTransaction{} }
func (*ResponsePrepareTransaction) ProtoMessage() {}
func (*ResponsePrepareTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_294224101de536c3, []int{2}
}
func (m *ResponsePrepareTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponsePrepareTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponsePrepareTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponsePrepareTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePrepareTransaction.Merge(m, src)
}
func (m *ResponsePrepareTransaction) XXX_Size() int {
	return m.Size()
}
func (m *ResponsePrepareTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePrepareTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePrepareTransaction proto.InternalMessageInfo

func (m *ResponsePrepareTransaction) GetTxJSON() string {
	if m != nil {
		return m.TxJSON
	}
	return ""
}

func (m *ResponsePrepareTransaction) GetInstructions() *Instructions {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type RequestSign struct {
	TxJSON string `protobuf:"bytes,1,opt,name=txJSON,proto3" json:"txJSON,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (m *RequestSign) Reset()      { *m = RequestSign{} }
func (*RequestSign) ProtoMessage() {}
func (*RequestSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_294224101de536c3, []int{3}
}
func (m *RequestSign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestSign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSign.Merge(m, src)
}
func (m *RequestSign) XXX_Size() int {
	return m.Size()
}
func (m *RequestSign) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSign.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSign proto.InternalMessageInfo

func (m *RequestSign) GetTxJSON() string {
	if m != nil {
		return m.TxJSON
	}
	return ""
}

func (m *RequestSign) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type ResponseSign struct {
	TxID   string `protobuf:"bytes,1,opt,name=txID,proto3" json:"txID,omitempty"`
	TxBlob string `protobuf:"bytes,2,opt,name=txBlob,proto3" json:"txBlob,omitempty"`
}

func (m *ResponseSign) Reset()      { *m = ResponseSign{} }
func (*ResponseSign) ProtoMessage() {}
func (*ResponseSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_294224101de536c3, []int{4}
}
func (m *ResponseSign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseSign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSign.Merge(m, src)
}
func (m *ResponseSign) XXX_Size() int {
	return m.Size()
}
func (m *ResponseSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSign.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSign proto.InternalMessageInfo

func (m *ResponseSign) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *ResponseSign) GetTxBlob() string {
	if m != nil {
		return m.TxBlob
	}
	return ""
}

func init() {
	proto.RegisterEnum("rippleapi.EnumTransactionType", EnumTransactionType_name, EnumTransactionType_value)
	proto.RegisterType((*Instructions)(nil), "rippleapi.Instructions")
	proto.RegisterType((*RequestPrepareTransaction)(nil), "rippleapi.RequestPrepareTransaction")
	proto.RegisterType((*ResponsePrepareTransaction)(nil), "rippleapi.ResponsePrepareTransaction")
	proto.RegisterType((*RequestSign)(nil), "rippleapi.RequestSign")
	proto.RegisterType((*ResponseSign)(nil), "rippleapi.ResponseSign")
}

func init() { proto.RegisterFile("rippleapi/rippleapi.proto", fileDescriptor_294224101de536c3) }

var fileDescriptor_294224101de536c3 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x8f, 0xda, 0x46,
	0x14, 0xb7, 0x17, 0x42, 0xc2, 0x5b, 0xfe, 0xcc, 0x4e, 0x5a, 0x96, 0xa5, 0xad, 0x15, 0xa1, 0x54,
	0x42, 0x91, 0x4a, 0xa5, 0xad, 0xd4, 0x4a, 0xad, 0x7a, 0xf0, 0x9a, 0x21, 0xb8, 0x21, 0x06, 0x8d,
	0x87, 0x96, 0xf4, 0x62, 0x19, 0x67, 0x20, 0x96, 0xc0, 0x76, 0x6c, 0x53, 0xb1, 0xb7, 0x7e, 0x84,
	0x7e, 0x8c, 0x5e, 0x7a, 0xed, 0x67, 0xe8, 0x71, 0x8f, 0x39, 0xf4, 0xd0, 0x65, 0x2f, 0x3d, 0xe6,
	0xda, 0x5b, 0xe5, 0x3f, 0x2c, 0x78, 0x17, 0x0e, 0x39, 0x79, 0xde, 0xef, 0xbd, 0xdf, 0x7b, 0x7e,
	0xbf, 0xf7, 0x66, 0xe0, 0xcc, 0xb7, 0x3d, 0x6f, 0xce, 0x4d, 0xcf, 0xfe, 0xf2, 0xf6, 0xd4, 0xf6,
	0x7c, 0x37, 0x74, 0x71, 0xf1, 0x16, 0x68, 0xfe, 0x2d, 0x42, 0x49, 0x75, 0x82, 0xd0, 0x5f, 0x5a,
	0xa1, 0xed, 0x3a, 0x01, 0x46, 0x90, 0x9b, 0x72, 0x5e, 0x17, 0x9f, 0x88, 0xad, 0x22, 0x8d, 0x8e,
	0xb8, 0x06, 0x85, 0x85, 0xb9, 0xea, 0x72, 0x5e, 0x3f, 0x8a, 0xc1, 0xd4, 0xc2, 0xcf, 0x00, 0x2d,
	0xcc, 0x55, 0x9f, 0xbf, 0x9e, 0x71, 0xff, 0x47, 0xee, 0x07, 0xb6, 0xeb, 0xd4, 0x73, 0x4f, 0xc4,
	0x56, 0x99, 0xde, 0xc3, 0xf1, 0xd7, 0x50, 0xbb, 0x8b, 0x0d, 0xa6, 0xd3, 0x80, 0x87, 0xf5, 0x7c,
	0xcc, 0x38, 0xe0, 0xc5, 0x0d, 0x78, 0x14, 0xf0, 0xb7, 0x4b, 0xee, 0x58, 0xbc, 0xfe, 0x20, 0x8e,
	0xbc, 0xb5, 0x71, 0x13, 0x4a, 0x81, 0x3d, 0x73, 0xb8, 0x1f, 0x28, 0xee, 0xd2, 0x09, 0xeb, 0x85,
	0xd8, 0x9f, 0xc1, 0x9a, 0xff, 0x89, 0x70, 0x46, 0x23, 0x42, 0x10, 0x0e, 0x7d, 0xee, 0x99, 0x3e,
	0x67, 0xbe, 0xe9, 0x04, 0x66, 0xdc, 0x2c, 0xfe, 0x06, 0x1e, 0x86, 0x2b, 0x23, 0xbc, 0xf4, 0x92,
	0x7e, 0x2b, 0xe7, 0x52, 0x7b, 0x2b, 0x15, 0x71, 0x96, 0x8b, 0x9d, 0x60, 0x76, 0xe9, 0x71, 0x5a,
	0x08, 0x57, 0xd1, 0x17, 0x3f, 0x85, 0x72, 0xc0, 0x9d, 0xd7, 0xdc, 0x97, 0x2d, 0x2b, 0xae, 0x9d,
	0x28, 0x93, 0x05, 0x23, 0xe1, 0xcc, 0x45, 0xec, 0x8e, 0x64, 0x11, 0x69, 0x6a, 0xe1, 0x16, 0x54,
	0x7d, 0x6e, 0x71, 0xfb, 0x97, 0x2d, 0x3f, 0x1f, 0xf3, 0xef, 0xc2, 0xf8, 0x3b, 0x28, 0xd9, 0x3b,
	0xc3, 0x89, 0x25, 0x38, 0x3e, 0x3f, 0xdd, 0xf9, 0xcb, 0xdd, 0xd9, 0xd1, 0x4c, 0x70, 0xf3, 0x2d,
	0x34, 0x28, 0x0f, 0x3c, 0xd7, 0x09, 0xf8, 0x9e, 0xde, 0x6b, 0x50, 0x08, 0x57, 0x3f, 0xe8, 0x03,
	0x2d, 0x1d, 0x75, 0x6a, 0xdd, 0x2b, 0x79, 0xf4, 0x21, 0x25, 0xbf, 0x87, 0xe3, 0x54, 0x6d, 0xdd,
	0x9e, 0x1d, 0xae, 0x51, 0x83, 0x42, 0xc0, 0x2d, 0x9f, 0x6f, 0x74, 0x4b, 0xad, 0xe6, 0xb7, 0x50,
	0xda, 0xfc, 0x71, 0xcc, 0xc7, 0x90, 0x0f, 0x57, 0x6a, 0x27, 0x65, 0xc7, 0xe7, 0x24, 0xe7, 0xc5,
	0xdc, 0x9d, 0x6c, 0xb8, 0x89, 0xf5, 0xec, 0x8f, 0x1c, 0x3c, 0xde, 0x33, 0x32, 0x8c, 0xa1, 0xc2,
	0xc6, 0x86, 0xac, 0x28, 0x83, 0x91, 0xc6, 0x0c, 0x9d, 0x30, 0x24, 0xe0, 0x8f, 0xe1, 0x64, 0x07,
	0xeb, 0x90, 0x3e, 0x61, 0x04, 0x89, 0xf8, 0x31, 0x54, 0xd9, 0xd8, 0x50, 0x7a, 0x44, 0x79, 0x61,
	0x28, 0xb2, 0xa6, 0x90, 0x3e, 0x3a, 0xc2, 0x27, 0x50, 0xde, 0x01, 0xf5, 0x1e, 0xca, 0x65, 0xe3,
	0x28, 0x91, 0x19, 0x41, 0x79, 0x5c, 0x03, 0xcc, 0xc6, 0x46, 0x87, 0x0c, 0x07, 0xba, 0xca, 0x8c,
	0x21, 0x25, 0xf2, 0x88, 0xf5, 0xd0, 0x03, 0xfc, 0x11, 0x20, 0x36, 0x36, 0x88, 0xae, 0xd0, 0xc1,
	0x4f, 0x9b, 0xac, 0x85, 0x3b, 0x68, 0x92, 0xe3, 0x61, 0x16, 0xed, 0xaa, 0x9a, 0xaa, 0xf7, 0xd0,
	0xa3, 0xb4, 0xdc, 0xa0, 0xdb, 0x25, 0x74, 0x93, 0xa0, 0x98, 0x05, 0x13, 0x3e, 0xe0, 0x0a, 0x00,
	0x1b, 0x1b, 0x43, 0xf9, 0xd5, 0x4b, 0xa2, 0x31, 0x74, 0x8c, 0x3f, 0x85, 0xfa, 0xd6, 0x36, 0x94,
	0x9e, 0xac, 0x69, 0xa4, 0x6f, 0x28, 0x7d, 0x59, 0x7d, 0x89, 0x4a, 0xf8, 0x33, 0x38, 0xdb, 0xe7,
	0x4d, 0x92, 0x95, 0xf1, 0x27, 0x70, 0xba, 0xc7, 0xdd, 0x1d, 0x69, 0x1d, 0x54, 0x49, 0xbb, 0xd5,
	0x09, 0x33, 0x28, 0x79, 0x3e, 0xea, 0xcb, 0xd4, 0x78, 0x41, 0x5e, 0xa1, 0xea, 0x06, 0x57, 0xb5,
	0xe7, 0x84, 0x1a, 0x7d, 0x55, 0x4f, 0x14, 0x47, 0x18, 0x41, 0x89, 0x8d, 0x0d, 0x46, 0x47, 0x29,
	0x72, 0x72, 0xfe, 0xa7, 0x08, 0x45, 0x1a, 0xef, 0x94, 0x3c, 0x54, 0xb1, 0x05, 0x78, 0xcf, 0x8e,
	0x3e, 0xdd, 0xd9, 0xba, 0x83, 0xb7, 0xb8, 0xf1, 0x79, 0x26, 0xea, 0xd0, 0xc2, 0x37, 0x05, 0xdc,
	0x81, 0x6a, 0xb4, 0x56, 0x99, 0x5b, 0x70, 0xbf, 0x42, 0x14, 0xd2, 0x38, 0xdd, 0x93, 0x33, 0x72,
	0x34, 0x85, 0x8b, 0xf0, 0xea, 0x5a, 0x12, 0xde, 0x5d, 0x4b, 0xc2, 0xfb, 0x6b, 0x49, 0xfc, 0x75,
	0x2d, 0x89, 0xbf, 0xaf, 0x25, 0xf1, 0xaf, 0xb5, 0x24, 0x5e, 0xad, 0x25, 0xf1, 0x9f, 0xb5, 0x24,
	0xfe, 0xbb, 0x96, 0x84, 0xf7, 0x6b, 0x49, 0xfc, 0xed, 0x46, 0x12, 0xae, 0x6e, 0x24, 0xe1, 0xdd,
	0x8d, 0x24, 0x40, 0xcb, 0x72, 0x17, 0xed, 0x99, 0x1d, 0xbe, 0x59, 0x4e, 0xda, 0x6f, 0x6c, 0xdf,
	0x5d, 0x98, 0xf6, 0xfc, 0x32, 0x2d, 0xf2, 0xc5, 0xdc, 0x9e, 0x24, 0x2f, 0xf3, 0x64, 0x39, 0xbd,
	0xd8, 0xaa, 0xf2, 0xf3, 0xf6, 0x9d, 0x9e, 0x14, 0x62, 0xff, 0x57, 0xff, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0x44, 0xfb, 0xf3, 0xd6, 0x05, 0x00, 0x00,
}

func (x EnumTransactionType) String() string {
	s, ok := EnumTransactionType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Instructions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Instructions)
	if !ok {
		that2, ok := that.(Instructions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Fee != that1.Fee {
		return false
	}
	if this.MaxFee != that1.MaxFee {
		return false
	}
	if this.MaxLedgerVersion != that1.MaxLedgerVersion {
		return false
	}
	if this.MaxLedgerVersionOffset != that1.MaxLedgerVersionOffset {
		return false
	}
	if this.Sequence != that1.Sequence {
		return false
	}
	if this.SignersCount != that1.SignersCount {
		return false
	}
	return true
}
func (this *RequestPrepareTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestPrepareTransaction)
	if !ok {
		that2, ok := that.(RequestPrepareTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxType != that1.TxType {
		return false
	}
	if this.SenderAccount != that1.SenderAccount {
		return false
	}
	if this.Amount != that1.Amount {
		return false
	}
	if this.ReceiverAccount != that1.ReceiverAccount {
		return false
	}
	if !this.Instructions.Equal(that1.Instructions) {
		return false
	}
	return true
}
func (this *ResponsePrepareTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponsePrepareTransaction)
	if !ok {
		that2, ok := that.(ResponsePrepareTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxJSON != that1.TxJSON {
		return false
	}
	if !this.Instructions.Equal(that1.Instructions) {
		return false
	}
	return true
}
func (this *RequestSign) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestSign)
	if !ok {
		that2, ok := that.(RequestSign)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxJSON != that1.TxJSON {
		return false
	}
	if this.Secret != that1.Secret {
		return false
	}
	return true
}
func (this *ResponseSign) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseSign)
	if !ok {
		that2, ok := that.(ResponseSign)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxID != that1.TxID {
		return false
	}
	if this.TxBlob != that1.TxBlob {
		return false
	}
	return true
}
func (this *Instructions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&rippleapi.Instructions{")
	s = append(s, "Fee: "+fmt.Sprintf("%#v", this.Fee)+",\n")
	s = append(s, "MaxFee: "+fmt.Sprintf("%#v", this.MaxFee)+",\n")
	s = append(s, "MaxLedgerVersion: "+fmt.Sprintf("%#v", this.MaxLedgerVersion)+",\n")
	s = append(s, "MaxLedgerVersionOffset: "+fmt.Sprintf("%#v", this.MaxLedgerVersionOffset)+",\n")
	s = append(s, "Sequence: "+fmt.Sprintf("%#v", this.Sequence)+",\n")
	s = append(s, "SignersCount: "+fmt.Sprintf("%#v", this.SignersCount)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestPrepareTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&rippleapi.RequestPrepareTransaction{")
	s = append(s, "TxType: "+fmt.Sprintf("%#v", this.TxType)+",\n")
	s = append(s, "SenderAccount: "+fmt.Sprintf("%#v", this.SenderAccount)+",\n")
	s = append(s, "Amount: "+fmt.Sprintf("%#v", this.Amount)+",\n")
	s = append(s, "ReceiverAccount: "+fmt.Sprintf("%#v", this.ReceiverAccount)+",\n")
	if this.Instructions != nil {
		s = append(s, "Instructions: "+fmt.Sprintf("%#v", this.Instructions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponsePrepareTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.ResponsePrepareTransaction{")
	s = append(s, "TxJSON: "+fmt.Sprintf("%#v", this.TxJSON)+",\n")
	if this.Instructions != nil {
		s = append(s, "Instructions: "+fmt.Sprintf("%#v", this.Instructions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestSign) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.RequestSign{")
	s = append(s, "TxJSON: "+fmt.Sprintf("%#v", this.TxJSON)+",\n")
	s = append(s, "Secret: "+fmt.Sprintf("%#v", this.Secret)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseSign) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.ResponseSign{")
	s = append(s, "TxID: "+fmt.Sprintf("%#v", this.TxID)+",\n")
	s = append(s, "TxBlob: "+fmt.Sprintf("%#v", this.TxBlob)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringRippleapi(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RippleAPIClient is the client API for RippleAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RippleAPIClient interface {
	// https://xrpl.org/rippleapi-reference.html#preparetransaction
	PrepareTransaction(ctx context.Context, in *RequestPrepareTransaction, opts ...grpc.CallOption) (*ResponsePrepareTransaction, error)
	SignTransaction(ctx context.Context, in *RequestSign, opts ...grpc.CallOption) (*ResponseSign, error)
}

type rippleAPIClient struct {
	cc *grpc.ClientConn
}

func NewRippleAPIClient(cc *grpc.ClientConn) RippleAPIClient {
	return &rippleAPIClient{cc}
}

func (c *rippleAPIClient) PrepareTransaction(ctx context.Context, in *RequestPrepareTransaction, opts ...grpc.CallOption) (*ResponsePrepareTransaction, error) {
	out := new(ResponsePrepareTransaction)
	err := c.cc.Invoke(ctx, "/rippleapi.RippleAPI/PrepareTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rippleAPIClient) SignTransaction(ctx context.Context, in *RequestSign, opts ...grpc.CallOption) (*ResponseSign, error) {
	out := new(ResponseSign)
	err := c.cc.Invoke(ctx, "/rippleapi.RippleAPI/SignTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RippleAPIServer is the server API for RippleAPI service.
type RippleAPIServer interface {
	// https://xrpl.org/rippleapi-reference.html#preparetransaction
	PrepareTransaction(context.Context, *RequestPrepareTransaction) (*ResponsePrepareTransaction, error)
	SignTransaction(context.Context, *RequestSign) (*ResponseSign, error)
}

// UnimplementedRippleAPIServer can be embedded to have forward compatible implementations.
type UnimplementedRippleAPIServer struct {
}

func (*UnimplementedRippleAPIServer) PrepareTransaction(ctx context.Context, req *RequestPrepareTransaction) (*ResponsePrepareTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTransaction not implemented")
}
func (*UnimplementedRippleAPIServer) SignTransaction(ctx context.Context, req *RequestSign) (*ResponseSign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTransaction not implemented")
}

func RegisterRippleAPIServer(s *grpc.Server, srv RippleAPIServer) {
	s.RegisterService(&_RippleAPI_serviceDesc, srv)
}

func _RippleAPI_PrepareTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPrepareTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RippleAPIServer).PrepareTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rippleapi.RippleAPI/PrepareTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RippleAPIServer).PrepareTransaction(ctx, req.(*RequestPrepareTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _RippleAPI_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RippleAPIServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rippleapi.RippleAPI/SignTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RippleAPIServer).SignTransaction(ctx, req.(*RequestSign))
	}
	return interceptor(ctx, in, info, handler)
}

var _RippleAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rippleapi.RippleAPI",
	HandlerType: (*RippleAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareTransaction",
			Handler:    _RippleAPI_PrepareTransaction_Handler,
		},
		{
			MethodName: "SignTransaction",
			Handler:    _RippleAPI_SignTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rippleapi/rippleapi.proto",
}

func (m *Instructions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Instructions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Instructions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignersCount != 0 {
		i = encodeVarintRippleapi(dAtA, i, uint64(m.SignersCount))
		i--
		dAtA[i] = 0x30
	}
	if m.Sequence != 0 {
		i = encodeVarintRippleapi(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxLedgerVersionOffset != 0 {
		i = encodeVarintRippleapi(dAtA, i, uint64(m.MaxLedgerVersionOffset))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxLedgerVersion != 0 {
		i = encodeVarintRippleapi(dAtA, i, uint64(m.MaxLedgerVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MaxFee) > 0 {
		i -= len(m.MaxFee)
		copy(dAtA[i:], m.MaxFee)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.MaxFee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestPrepareTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestPrepareTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestPrepareTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Instructions != nil {
		{
			size, err := m.Instructions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRippleapi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReceiverAccount) > 0 {
		i -= len(m.ReceiverAccount)
		copy(dAtA[i:], m.ReceiverAccount)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.ReceiverAccount)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Amount))))
		i--
		dAtA[i] = 0x19
	}
	if len(m.SenderAccount) > 0 {
		i -= len(m.SenderAccount)
		copy(dAtA[i:], m.SenderAccount)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.SenderAccount)))
		i--
		dAtA[i] = 0x12
	}
	if m.TxType != 0 {
		i = encodeVarintRippleapi(dAtA, i, uint64(m.TxType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ResponsePrepareTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponsePrepareTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponsePrepareTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Instructions != nil {
		{
			size, err := m.Instructions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRippleapi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxJSON) > 0 {
		i -= len(m.TxJSON)
		copy(dAtA[i:], m.TxJSON)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.TxJSON)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestSign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestSign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestSign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Secret) > 0 {
		i -= len(m.Secret)
		copy(dAtA[i:], m.Secret)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.Secret)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxJSON) > 0 {
		i -= len(m.TxJSON)
		copy(dAtA[i:], m.TxJSON)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.TxJSON)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResponseSign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseSign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseSign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxBlob) > 0 {
		i -= len(m.TxBlob)
		copy(dAtA[i:], m.TxBlob)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.TxBlob)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxID) > 0 {
		i -= len(m.TxID)
		copy(dAtA[i:], m.TxID)
		i = encodeVarintRippleapi(dAtA, i, uint64(len(m.TxID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRippleapi(dAtA []byte, offset int, v uint64) int {
	offset -= sovRippleapi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Instructions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	l = len(m.MaxFee)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	if m.MaxLedgerVersion != 0 {
		n += 1 + sovRippleapi(uint64(m.MaxLedgerVersion))
	}
	if m.MaxLedgerVersionOffset != 0 {
		n += 1 + sovRippleapi(uint64(m.MaxLedgerVersionOffset))
	}
	if m.Sequence != 0 {
		n += 1 + sovRippleapi(uint64(m.Sequence))
	}
	if m.SignersCount != 0 {
		n += 1 + sovRippleapi(uint64(m.SignersCount))
	}
	return n
}

func (m *RequestPrepareTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxType != 0 {
		n += 1 + sovRippleapi(uint64(m.TxType))
	}
	l = len(m.SenderAccount)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	if m.Amount != 0 {
		n += 9
	}
	l = len(m.ReceiverAccount)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	if m.Instructions != nil {
		l = m.Instructions.Size()
		n += 1 + l + sovRippleapi(uint64(l))
	}
	return n
}

func (m *ResponsePrepareTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxJSON)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	if m.Instructions != nil {
		l = m.Instructions.Size()
		n += 1 + l + sovRippleapi(uint64(l))
	}
	return n
}

func (m *RequestSign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxJSON)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	l = len(m.Secret)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	return n
}

func (m *ResponseSign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxID)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	l = len(m.TxBlob)
	if l > 0 {
		n += 1 + l + sovRippleapi(uint64(l))
	}
	return n
}

func sovRippleapi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRippleapi(x uint64) (n int) {
	return sovRippleapi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Instructions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Instructions{`,
		`Fee:` + fmt.Sprintf("%v", this.Fee) + `,`,
		`MaxFee:` + fmt.Sprintf("%v", this.MaxFee) + `,`,
		`MaxLedgerVersion:` + fmt.Sprintf("%v", this.MaxLedgerVersion) + `,`,
		`MaxLedgerVersionOffset:` + fmt.Sprintf("%v", this.MaxLedgerVersionOffset) + `,`,
		`Sequence:` + fmt.Sprintf("%v", this.Sequence) + `,`,
		`SignersCount:` + fmt.Sprintf("%v", this.SignersCount) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestPrepareTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestPrepareTransaction{`,
		`TxType:` + fmt.Sprintf("%v", this.TxType) + `,`,
		`SenderAccount:` + fmt.Sprintf("%v", this.SenderAccount) + `,`,
		`Amount:` + fmt.Sprintf("%v", this.Amount) + `,`,
		`ReceiverAccount:` + fmt.Sprintf("%v", this.ReceiverAccount) + `,`,
		`Instructions:` + strings.Replace(this.Instructions.String(), "Instructions", "Instructions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponsePrepareTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponsePrepareTransaction{`,
		`TxJSON:` + fmt.Sprintf("%v", this.TxJSON) + `,`,
		`Instructions:` + strings.Replace(this.Instructions.String(), "Instructions", "Instructions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestSign) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestSign{`,
		`TxJSON:` + fmt.Sprintf("%v", this.TxJSON) + `,`,
		`Secret:` + fmt.Sprintf("%v", this.Secret) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseSign) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponseSign{`,
		`TxID:` + fmt.Sprintf("%v", this.TxID) + `,`,
		`TxBlob:` + fmt.Sprintf("%v", this.TxBlob) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringRippleapi(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Instructions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRippleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Instructions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Instructions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLedgerVersion", wireType)
			}
			m.MaxLedgerVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLedgerVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLedgerVersionOffset", wireType)
			}
			m.MaxLedgerVersionOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLedgerVersionOffset |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignersCount", wireType)
			}
			m.SignersCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignersCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRippleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestPrepareTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRippleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestPrepareTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestPrepareTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxType", wireType)
			}
			m.TxType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxType |= EnumTransactionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Amount = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instructions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Instructions == nil {
				m.Instructions = &Instructions{}
			}
			if err := m.Instructions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRippleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponsePrepareTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRippleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponsePrepareTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponsePrepareTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxJSON", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxJSON = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instructions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Instructions == nil {
				m.Instructions = &Instructions{}
			}
			if err := m.Instructions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRippleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestSign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRippleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestSign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestSign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxJSON", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxJSON = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secret", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Secret = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRippleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseSign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRippleapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseSign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseSign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBlob", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRippleapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRippleapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxBlob = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRippleapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRippleapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRippleapi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRippleapi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRippleapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRippleapi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRippleapi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRippleapi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRippleapi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRippleapi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRippleapi = fmt.Errorf("proto: unexpected end of group")
)
