// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rippleapi/transaction.proto

package rippleapi

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EnumTransactionType int32

const (
	TX_ACCOUNT_SET            EnumTransactionType = 0
	TX_ACCOUNT_DELETE         EnumTransactionType = 1
	TX_CHECK_CANCEL           EnumTransactionType = 2
	TX_CHECK_CASH             EnumTransactionType = 3
	TX_CHECK_CREATE           EnumTransactionType = 4
	TX_DEPOSIT_PREAUTH        EnumTransactionType = 5
	TX_ESCROW_CANCEL          EnumTransactionType = 6
	TX_ESCROW_CREATE          EnumTransactionType = 7
	TX_ESCROW_FINISH          EnumTransactionType = 8
	TX_OFFER_CANCEL           EnumTransactionType = 9
	TX_OFFER_CREATE           EnumTransactionType = 10
	TX_PAYMENT                EnumTransactionType = 11
	TX_PAYMENT_CHANNEL_CLAIM  EnumTransactionType = 12
	TX_PAYMENT_CHANNEL_CREATE EnumTransactionType = 13
	TX_PAYMENT_CHANNEL_FUND   EnumTransactionType = 14
	TX_SET_REGULAR_KEY        EnumTransactionType = 15
	TX_SINGER_LIST_SET        EnumTransactionType = 16
	TX_TRUST_SET              EnumTransactionType = 17
)

var EnumTransactionType_name = map[int32]string{
	0:  "TX_ACCOUNT_SET",
	1:  "TX_ACCOUNT_DELETE",
	2:  "TX_CHECK_CANCEL",
	3:  "TX_CHECK_CASH",
	4:  "TX_CHECK_CREATE",
	5:  "TX_DEPOSIT_PREAUTH",
	6:  "TX_ESCROW_CANCEL",
	7:  "TX_ESCROW_CREATE",
	8:  "TX_ESCROW_FINISH",
	9:  "TX_OFFER_CANCEL",
	10: "TX_OFFER_CREATE",
	11: "TX_PAYMENT",
	12: "TX_PAYMENT_CHANNEL_CLAIM",
	13: "TX_PAYMENT_CHANNEL_CREATE",
	14: "TX_PAYMENT_CHANNEL_FUND",
	15: "TX_SET_REGULAR_KEY",
	16: "TX_SINGER_LIST_SET",
	17: "TX_TRUST_SET",
}

var EnumTransactionType_value = map[string]int32{
	"TX_ACCOUNT_SET":            0,
	"TX_ACCOUNT_DELETE":         1,
	"TX_CHECK_CANCEL":           2,
	"TX_CHECK_CASH":             3,
	"TX_CHECK_CREATE":           4,
	"TX_DEPOSIT_PREAUTH":        5,
	"TX_ESCROW_CANCEL":          6,
	"TX_ESCROW_CREATE":          7,
	"TX_ESCROW_FINISH":          8,
	"TX_OFFER_CANCEL":           9,
	"TX_OFFER_CREATE":           10,
	"TX_PAYMENT":                11,
	"TX_PAYMENT_CHANNEL_CLAIM":  12,
	"TX_PAYMENT_CHANNEL_CREATE": 13,
	"TX_PAYMENT_CHANNEL_FUND":   14,
	"TX_SET_REGULAR_KEY":        15,
	"TX_SINGER_LIST_SET":        16,
	"TX_TRUST_SET":              17,
}

func (EnumTransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{0}
}

type Instructions struct {
	Fee                    string `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	MaxFee                 string `protobuf:"bytes,2,opt,name=maxFee,proto3" json:"maxFee,omitempty"`
	MaxLedgerVersion       uint64 `protobuf:"varint,3,opt,name=maxLedgerVersion,proto3" json:"maxLedgerVersion,omitempty"`
	MaxLedgerVersionOffset uint64 `protobuf:"varint,4,opt,name=maxLedgerVersionOffset,proto3" json:"maxLedgerVersionOffset,omitempty"`
	Sequence               uint64 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SignersCount           uint64 `protobuf:"varint,6,opt,name=signersCount,proto3" json:"signersCount,omitempty"`
}

func (m *Instructions) Reset()      { *m = Instructions{} }
func (*Instructions) ProtoMessage() {}
func (*Instructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{0}
}
func (m *Instructions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Instructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Instructions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Instructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instructions.Merge(m, src)
}
func (m *Instructions) XXX_Size() int {
	return m.Size()
}
func (m *Instructions) XXX_DiscardUnknown() {
	xxx_messageInfo_Instructions.DiscardUnknown(m)
}

var xxx_messageInfo_Instructions proto.InternalMessageInfo

func (m *Instructions) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *Instructions) GetMaxFee() string {
	if m != nil {
		return m.MaxFee
	}
	return ""
}

func (m *Instructions) GetMaxLedgerVersion() uint64 {
	if m != nil {
		return m.MaxLedgerVersion
	}
	return 0
}

func (m *Instructions) GetMaxLedgerVersionOffset() uint64 {
	if m != nil {
		return m.MaxLedgerVersionOffset
	}
	return 0
}

func (m *Instructions) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Instructions) GetSignersCount() uint64 {
	if m != nil {
		return m.SignersCount
	}
	return 0
}

type RequestPrepareTransaction struct {
	TxType        EnumTransactionType `protobuf:"varint,1,opt,name=tx_type,json=txType,proto3,enum=rippleapi.transaction.EnumTransactionType" json:"tx_type,omitempty"`
	SenderAccount string              `protobuf:"bytes,2,opt,name=senderAccount,proto3" json:"senderAccount,omitempty"`
	Amount        float64             `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	//float amount = 3;
	ReceiverAccount string        `protobuf:"bytes,4,opt,name=receiverAccount,proto3" json:"receiverAccount,omitempty"`
	Instructions    *Instructions `protobuf:"bytes,5,opt,name=instructions,proto3" json:"instructions,omitempty"`
}

func (m *RequestPrepareTransaction) Reset()      { *m = RequestPrepareTransaction{} }
func (*RequestPrepareTransaction) ProtoMessage() {}
func (*RequestPrepareTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{1}
}
func (m *RequestPrepareTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestPrepareTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestPrepareTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestPrepareTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPrepareTransaction.Merge(m, src)
}
func (m *RequestPrepareTransaction) XXX_Size() int {
	return m.Size()
}
func (m *RequestPrepareTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPrepareTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPrepareTransaction proto.InternalMessageInfo

func (m *RequestPrepareTransaction) GetTxType() EnumTransactionType {
	if m != nil {
		return m.TxType
	}
	return TX_ACCOUNT_SET
}

func (m *RequestPrepareTransaction) GetSenderAccount() string {
	if m != nil {
		return m.SenderAccount
	}
	return ""
}

func (m *RequestPrepareTransaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RequestPrepareTransaction) GetReceiverAccount() string {
	if m != nil {
		return m.ReceiverAccount
	}
	return ""
}

func (m *RequestPrepareTransaction) GetInstructions() *Instructions {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type ResponsePrepareTransaction struct {
	TxJSON       string        `protobuf:"bytes,1,opt,name=txJSON,proto3" json:"txJSON,omitempty"`
	Instructions *Instructions `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
}

func (m *ResponsePrepareTransaction) Reset()      { *m = ResponsePrepareTransaction{} }
func (*ResponsePrepareTransaction) ProtoMessage() {}
func (*ResponsePrepareTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{2}
}
func (m *ResponsePrepareTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponsePrepareTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponsePrepareTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponsePrepareTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePrepareTransaction.Merge(m, src)
}
func (m *ResponsePrepareTransaction) XXX_Size() int {
	return m.Size()
}
func (m *ResponsePrepareTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePrepareTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePrepareTransaction proto.InternalMessageInfo

func (m *ResponsePrepareTransaction) GetTxJSON() string {
	if m != nil {
		return m.TxJSON
	}
	return ""
}

func (m *ResponsePrepareTransaction) GetInstructions() *Instructions {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type RequestSignTransaction struct {
	TxJSON string `protobuf:"bytes,1,opt,name=txJSON,proto3" json:"txJSON,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (m *RequestSignTransaction) Reset()      { *m = RequestSignTransaction{} }
func (*RequestSignTransaction) ProtoMessage() {}
func (*RequestSignTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{3}
}
func (m *RequestSignTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestSignTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestSignTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestSignTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSignTransaction.Merge(m, src)
}
func (m *RequestSignTransaction) XXX_Size() int {
	return m.Size()
}
func (m *RequestSignTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSignTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSignTransaction proto.InternalMessageInfo

func (m *RequestSignTransaction) GetTxJSON() string {
	if m != nil {
		return m.TxJSON
	}
	return ""
}

func (m *RequestSignTransaction) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type ResponseSignTransaction struct {
	TxID   string `protobuf:"bytes,1,opt,name=txID,proto3" json:"txID,omitempty"`
	TxBlob string `protobuf:"bytes,2,opt,name=txBlob,proto3" json:"txBlob,omitempty"`
}

func (m *ResponseSignTransaction) Reset()      { *m = ResponseSignTransaction{} }
func (*ResponseSignTransaction) ProtoMessage() {}
func (*ResponseSignTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{4}
}
func (m *ResponseSignTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseSignTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseSignTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseSignTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSignTransaction.Merge(m, src)
}
func (m *ResponseSignTransaction) XXX_Size() int {
	return m.Size()
}
func (m *ResponseSignTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSignTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSignTransaction proto.InternalMessageInfo

func (m *ResponseSignTransaction) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *ResponseSignTransaction) GetTxBlob() string {
	if m != nil {
		return m.TxBlob
	}
	return ""
}

type RequestSubmitTransaction struct {
	TxBlob string `protobuf:"bytes,1,opt,name=txBlob,proto3" json:"txBlob,omitempty"`
}

func (m *RequestSubmitTransaction) Reset()      { *m = RequestSubmitTransaction{} }
func (*RequestSubmitTransaction) ProtoMessage() {}
func (*RequestSubmitTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{5}
}
func (m *RequestSubmitTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestSubmitTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestSubmitTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestSubmitTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSubmitTransaction.Merge(m, src)
}
func (m *RequestSubmitTransaction) XXX_Size() int {
	return m.Size()
}
func (m *RequestSubmitTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSubmitTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSubmitTransaction proto.InternalMessageInfo

func (m *RequestSubmitTransaction) GetTxBlob() string {
	if m != nil {
		return m.TxBlob
	}
	return ""
}

type ResponseSubmitTransaction struct {
	ResultJSONString      string `protobuf:"bytes,1,opt,name=resultJSONString,proto3" json:"resultJSONString,omitempty"`
	EarliestLedgerVersion uint64 `protobuf:"varint,2,opt,name=earliestLedgerVersion,proto3" json:"earliestLedgerVersion,omitempty"`
}

func (m *ResponseSubmitTransaction) Reset()      { *m = ResponseSubmitTransaction{} }
func (*ResponseSubmitTransaction) ProtoMessage() {}
func (*ResponseSubmitTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{6}
}
func (m *ResponseSubmitTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseSubmitTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseSubmitTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseSubmitTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSubmitTransaction.Merge(m, src)
}
func (m *ResponseSubmitTransaction) XXX_Size() int {
	return m.Size()
}
func (m *ResponseSubmitTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSubmitTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSubmitTransaction proto.InternalMessageInfo

func (m *ResponseSubmitTransaction) GetResultJSONString() string {
	if m != nil {
		return m.ResultJSONString
	}
	return ""
}

func (m *ResponseSubmitTransaction) GetEarliestLedgerVersion() uint64 {
	if m != nil {
		return m.EarliestLedgerVersion
	}
	return 0
}

type ResponseWaitValidation struct {
	LedgerVersion uint64 `protobuf:"varint,1,opt,name=ledgerVersion,proto3" json:"ledgerVersion,omitempty"`
}

func (m *ResponseWaitValidation) Reset()      { *m = ResponseWaitValidation{} }
func (*ResponseWaitValidation) ProtoMessage() {}
func (*ResponseWaitValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{7}
}
func (m *ResponseWaitValidation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseWaitValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseWaitValidation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseWaitValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWaitValidation.Merge(m, src)
}
func (m *ResponseWaitValidation) XXX_Size() int {
	return m.Size()
}
func (m *ResponseWaitValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWaitValidation.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWaitValidation proto.InternalMessageInfo

func (m *ResponseWaitValidation) GetLedgerVersion() uint64 {
	if m != nil {
		return m.LedgerVersion
	}
	return 0
}

type RequestGetTransaction struct {
	TxID             string `protobuf:"bytes,1,opt,name=txID,proto3" json:"txID,omitempty"`
	MinLedgerVersion uint64 `protobuf:"varint,2,opt,name=minLedgerVersion,proto3" json:"minLedgerVersion,omitempty"`
}

func (m *RequestGetTransaction) Reset()      { *m = RequestGetTransaction{} }
func (*RequestGetTransaction) ProtoMessage() {}
func (*RequestGetTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{8}
}
func (m *RequestGetTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestGetTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestGetTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestGetTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetTransaction.Merge(m, src)
}
func (m *RequestGetTransaction) XXX_Size() int {
	return m.Size()
}
func (m *RequestGetTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetTransaction proto.InternalMessageInfo

func (m *RequestGetTransaction) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *RequestGetTransaction) GetMinLedgerVersion() uint64 {
	if m != nil {
		return m.MinLedgerVersion
	}
	return 0
}

type ResponseGetTransaction struct {
	ResultJSONString string `protobuf:"bytes,1,opt,name=resultJSONString,proto3" json:"resultJSONString,omitempty"`
}

func (m *ResponseGetTransaction) Reset()      { *m = ResponseGetTransaction{} }
func (*ResponseGetTransaction) ProtoMessage() {}
func (*ResponseGetTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{9}
}
func (m *ResponseGetTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseGetTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseGetTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseGetTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetTransaction.Merge(m, src)
}
func (m *ResponseGetTransaction) XXX_Size() int {
	return m.Size()
}
func (m *ResponseGetTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetTransaction proto.InternalMessageInfo

func (m *ResponseGetTransaction) GetResultJSONString() string {
	if m != nil {
		return m.ResultJSONString
	}
	return ""
}

type RequestCombineTransaction struct {
	SignedTransactions []string `protobuf:"bytes,1,rep,name=signedTransactions,proto3" json:"signedTransactions,omitempty"`
}

func (m *RequestCombineTransaction) Reset()      { *m = RequestCombineTransaction{} }
func (*RequestCombineTransaction) ProtoMessage() {}
func (*RequestCombineTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{10}
}
func (m *RequestCombineTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestCombineTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestCombineTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestCombineTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCombineTransaction.Merge(m, src)
}
func (m *RequestCombineTransaction) XXX_Size() int {
	return m.Size()
}
func (m *RequestCombineTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCombineTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCombineTransaction proto.InternalMessageInfo

func (m *RequestCombineTransaction) GetSignedTransactions() []string {
	if m != nil {
		return m.SignedTransactions
	}
	return nil
}

type ResponseCombineTransaction struct {
	SignedTransaction string `protobuf:"bytes,1,opt,name=signedTransaction,proto3" json:"signedTransaction,omitempty"`
	TxID              string `protobuf:"bytes,2,opt,name=txID,proto3" json:"txID,omitempty"`
}

func (m *ResponseCombineTransaction) Reset()      { *m = ResponseCombineTransaction{} }
func (*ResponseCombineTransaction) ProtoMessage() {}
func (*ResponseCombineTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f692921b4448d7b, []int{11}
}
func (m *ResponseCombineTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResponseCombineTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResponseCombineTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResponseCombineTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCombineTransaction.Merge(m, src)
}
func (m *ResponseCombineTransaction) XXX_Size() int {
	return m.Size()
}
func (m *ResponseCombineTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCombineTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCombineTransaction proto.InternalMessageInfo

func (m *ResponseCombineTransaction) GetSignedTransaction() string {
	if m != nil {
		return m.SignedTransaction
	}
	return ""
}

func (m *ResponseCombineTransaction) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func init() {
	proto.RegisterEnum("rippleapi.transaction.EnumTransactionType", EnumTransactionType_name, EnumTransactionType_value)
	proto.RegisterType((*Instructions)(nil), "rippleapi.transaction.Instructions")
	proto.RegisterType((*RequestPrepareTransaction)(nil), "rippleapi.transaction.RequestPrepareTransaction")
	proto.RegisterType((*ResponsePrepareTransaction)(nil), "rippleapi.transaction.ResponsePrepareTransaction")
	proto.RegisterType((*RequestSignTransaction)(nil), "rippleapi.transaction.RequestSignTransaction")
	proto.RegisterType((*ResponseSignTransaction)(nil), "rippleapi.transaction.ResponseSignTransaction")
	proto.RegisterType((*RequestSubmitTransaction)(nil), "rippleapi.transaction.RequestSubmitTransaction")
	proto.RegisterType((*ResponseSubmitTransaction)(nil), "rippleapi.transaction.ResponseSubmitTransaction")
	proto.RegisterType((*ResponseWaitValidation)(nil), "rippleapi.transaction.ResponseWaitValidation")
	proto.RegisterType((*RequestGetTransaction)(nil), "rippleapi.transaction.RequestGetTransaction")
	proto.RegisterType((*ResponseGetTransaction)(nil), "rippleapi.transaction.ResponseGetTransaction")
	proto.RegisterType((*RequestCombineTransaction)(nil), "rippleapi.transaction.RequestCombineTransaction")
	proto.RegisterType((*ResponseCombineTransaction)(nil), "rippleapi.transaction.ResponseCombineTransaction")
}

func init() { proto.RegisterFile("rippleapi/transaction.proto", fileDescriptor_5f692921b4448d7b) }

var fileDescriptor_5f692921b4448d7b = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x26, 0x65, 0x5b, 0x89, 0x27, 0xb6, 0x4c, 0x6f, 0x62, 0x45, 0x91, 0xdf, 0x97, 0x35, 0xd8,
	0x1c, 0x0c, 0x23, 0xa6, 0x5d, 0xb7, 0xe8, 0xb1, 0x00, 0x4d, 0xaf, 0x2c, 0xd5, 0x8a, 0x24, 0x90,
	0x54, 0xac, 0xb4, 0x40, 0x09, 0x4a, 0x5e, 0x2b, 0x04, 0x24, 0x52, 0x25, 0x57, 0x81, 0x8c, 0x22,
	0x40, 0x7f, 0x42, 0xfb, 0x2f, 0x7a, 0xe9, 0xff, 0xe8, 0xa1, 0x07, 0x1f, 0x73, 0xe8, 0xa1, 0x96,
	0x2f, 0x3d, 0xe6, 0x27, 0x14, 0xfc, 0xd0, 0x07, 0x3f, 0x14, 0xb5, 0x3d, 0x59, 0xf3, 0xcc, 0x3c,
	0x33, 0xb3, 0xcf, 0xce, 0x8e, 0x09, 0xbb, 0x8e, 0x39, 0x18, 0xf4, 0x88, 0x31, 0x30, 0x8f, 0xa8,
	0x63, 0x58, 0xae, 0xd1, 0xa1, 0xa6, 0x6d, 0x89, 0x03, 0xc7, 0xa6, 0x36, 0xda, 0x99, 0x3a, 0xc5,
	0x39, 0x67, 0x71, 0xb7, 0x6b, 0xdb, 0xdd, 0x1e, 0x39, 0xf2, 0x83, 0xda, 0xc3, 0xeb, 0x23, 0xd2,
	0x1f, 0xd0, 0x9b, 0x80, 0x23, 0xfc, 0xc1, 0xc2, 0x46, 0xc5, 0x72, 0xa9, 0x33, 0xf4, 0x83, 0x5d,
	0xc4, 0xc1, 0xca, 0x35, 0x21, 0x05, 0x76, 0x8f, 0xdd, 0x5f, 0x57, 0xbc, 0x9f, 0x28, 0x0f, 0xd9,
	0xbe, 0x31, 0x2a, 0x11, 0x52, 0xc8, 0xf8, 0x60, 0x68, 0xa1, 0x03, 0xe0, 0xfa, 0xc6, 0xa8, 0x4a,
	0xae, 0xba, 0xc4, 0x79, 0x45, 0x1c, 0xd7, 0xb4, 0xad, 0xc2, 0xca, 0x1e, 0xbb, 0xbf, 0xaa, 0x24,
	0x70, 0xf4, 0x25, 0xe4, 0xe3, 0x58, 0xfd, 0xfa, 0xda, 0x25, 0xb4, 0xb0, 0xea, 0x33, 0x16, 0x78,
	0x51, 0x11, 0x1e, 0xba, 0xe4, 0xfb, 0x21, 0xb1, 0x3a, 0xa4, 0xb0, 0xe6, 0x47, 0x4e, 0x6d, 0x24,
	0xc0, 0x86, 0x6b, 0x76, 0x2d, 0xe2, 0xb8, 0xb2, 0x3d, 0xb4, 0x68, 0x21, 0xeb, 0xfb, 0x23, 0x98,
	0xf0, 0x73, 0x06, 0x9e, 0x29, 0x1e, 0xc1, 0xa5, 0x0d, 0x87, 0x0c, 0x0c, 0x87, 0x68, 0x33, 0x65,
	0x90, 0x0c, 0x0f, 0xe8, 0x48, 0xa7, 0x37, 0x83, 0xe0, 0xbc, 0xb9, 0x93, 0x03, 0x31, 0x55, 0x42,
	0x11, 0x5b, 0xc3, 0xfe, 0x1c, 0x51, 0xbb, 0x19, 0x10, 0x25, 0x4b, 0x47, 0xde, 0x5f, 0xf4, 0x1c,
	0x36, 0x5d, 0x62, 0x5d, 0x11, 0x47, 0xea, 0x74, 0xfc, 0x3e, 0x02, 0x95, 0xa2, 0xa0, 0x27, 0xa2,
	0xd1, 0xf7, 0xdd, 0x9e, 0x44, 0xac, 0x12, 0x5a, 0x68, 0x1f, 0xb6, 0x1c, 0xd2, 0x21, 0xe6, 0xdb,
	0x19, 0x7f, 0xd5, 0xe7, 0xc7, 0x61, 0x74, 0x0e, 0x1b, 0xe6, 0xdc, 0x45, 0xf9, 0x72, 0x3c, 0x3a,
	0xf9, 0x74, 0x41, 0xc7, 0xf3, 0x77, 0xaa, 0x44, 0x88, 0xc2, 0x3b, 0x28, 0x2a, 0xc4, 0x1d, 0xd8,
	0x96, 0x4b, 0x52, 0x34, 0xc9, 0x43, 0x96, 0x8e, 0xbe, 0x56, 0xeb, 0xb5, 0x70, 0x04, 0x42, 0x2b,
	0x51, 0x3e, 0xf3, 0x5f, 0xcb, 0x97, 0x21, 0x1f, 0xde, 0x88, 0x6a, 0x76, 0xad, 0x7f, 0x52, 0x3a,
	0x0f, 0x59, 0x97, 0x74, 0x1c, 0x32, 0x91, 0x36, 0xb4, 0x04, 0x0c, 0x4f, 0x27, 0x07, 0x89, 0xa7,
	0x42, 0xb0, 0x4a, 0x47, 0x95, 0xb3, 0x30, 0x91, 0xff, 0x3b, 0x48, 0x7f, 0xda, 0xb3, 0xdb, 0x93,
	0x34, 0x81, 0x25, 0x9c, 0x40, 0x61, 0xd2, 0xd0, 0xb0, 0xdd, 0x37, 0x69, 0xa2, 0x25, 0x9f, 0xc3,
	0x46, 0x38, 0xef, 0xbc, 0xb1, 0x0a, 0x4b, 0x27, 0x48, 0x07, 0xc0, 0x39, 0xc4, 0x1d, 0xf6, 0xa8,
	0xd7, 0xbd, 0x4a, 0x1d, 0xd3, 0xea, 0x86, 0xf4, 0x04, 0x8e, 0xbe, 0x80, 0x1d, 0x62, 0x38, 0x3d,
	0x93, 0xb8, 0x34, 0xfa, 0x92, 0x32, 0xfe, 0x34, 0xa7, 0x3b, 0x85, 0xaf, 0x3c, 0x0d, 0x83, 0xf2,
	0x97, 0x86, 0x49, 0x5f, 0x19, 0x3d, 0xf3, 0xca, 0xf0, 0x6b, 0x3f, 0x87, 0xcd, 0x5e, 0x24, 0x0f,
	0xeb, 0xe7, 0x89, 0x82, 0xc2, 0x25, 0xec, 0x84, 0x47, 0x3e, 0x27, 0x74, 0x99, 0x6e, 0xde, 0x3b,
	0x37, 0xad, 0xb4, 0xee, 0x12, 0xb8, 0x70, 0x36, 0x6b, 0x2c, 0x96, 0xf9, 0x5f, 0x88, 0x22, 0x5c,
	0x4c, 0x1f, 0xad, 0x6c, 0xf7, 0xdb, 0xa6, 0x15, 0x19, 0x50, 0x11, 0x90, 0xff, 0xc4, 0xaf, 0xe6,
	0x40, 0xb7, 0xc0, 0xee, 0xad, 0xec, 0xaf, 0x2b, 0x29, 0x1e, 0xe1, 0xbb, 0xd9, 0xb8, 0xa7, 0x64,
	0x7b, 0x01, 0xdb, 0x09, 0x4e, 0xd8, 0x57, 0xd2, 0x31, 0x95, 0x27, 0x33, 0x93, 0xe7, 0xe0, 0xd7,
	0x15, 0x78, 0x9c, 0xb2, 0x1f, 0x10, 0x82, 0x9c, 0xd6, 0xd2, 0x25, 0x59, 0xae, 0x37, 0x6b, 0x9a,
	0xae, 0x62, 0x8d, 0x63, 0xd0, 0x0e, 0x6c, 0xcf, 0x61, 0x67, 0xb8, 0x8a, 0x35, 0xcc, 0xb1, 0xe8,
	0x31, 0x6c, 0x69, 0x2d, 0x5d, 0x2e, 0x63, 0xf9, 0x42, 0x97, 0xa5, 0x9a, 0x8c, 0xab, 0x5c, 0x06,
	0x6d, 0xc3, 0xe6, 0x1c, 0xa8, 0x96, 0xb9, 0x95, 0x68, 0x9c, 0x82, 0x25, 0x0d, 0x73, 0xab, 0x28,
	0x0f, 0x48, 0x6b, 0xe9, 0x67, 0xb8, 0x51, 0x57, 0x2b, 0x9a, 0xde, 0x50, 0xb0, 0xd4, 0xd4, 0xca,
	0xdc, 0x1a, 0x7a, 0x02, 0x9c, 0xd6, 0xd2, 0xb1, 0x2a, 0x2b, 0xf5, 0xcb, 0x49, 0xd6, 0x6c, 0x0c,
	0x0d, 0x72, 0x3c, 0x88, 0xa2, 0xa5, 0x4a, 0xad, 0xa2, 0x96, 0xb9, 0x87, 0x61, 0xb9, 0x7a, 0xa9,
	0x84, 0x95, 0x49, 0x82, 0xf5, 0x28, 0x18, 0xf0, 0x01, 0xe5, 0x00, 0xb4, 0x96, 0xde, 0x90, 0x5e,
	0xbf, 0xc4, 0x35, 0x8d, 0x7b, 0x84, 0xfe, 0x07, 0x85, 0x99, 0xad, 0xcb, 0x65, 0xa9, 0x56, 0xc3,
	0x55, 0x5d, 0xae, 0x4a, 0x95, 0x97, 0xdc, 0x06, 0xfa, 0x3f, 0x3c, 0x4b, 0xf3, 0x06, 0xc9, 0x36,
	0xd1, 0x2e, 0x3c, 0x4d, 0x71, 0x97, 0x9a, 0xb5, 0x33, 0x2e, 0x17, 0x9e, 0x56, 0xc5, 0x9a, 0xae,
	0xe0, 0xf3, 0x66, 0x55, 0x52, 0xf4, 0x0b, 0xfc, 0x9a, 0xdb, 0x9a, 0xe0, 0x95, 0xda, 0x39, 0x56,
	0xf4, 0x6a, 0x45, 0x0d, 0x14, 0xe7, 0x10, 0x07, 0x1b, 0x5a, 0x4b, 0xd7, 0x94, 0x66, 0x88, 0x6c,
	0x9f, 0xfc, 0xbe, 0x06, 0x4f, 0x14, 0x7f, 0x69, 0xcd, 0xdd, 0x98, 0xd4, 0xa8, 0xa0, 0x1f, 0x00,
	0xa5, 0xec, 0xc3, 0xe3, 0x05, 0x1b, 0x6e, 0xe1, 0x7f, 0x95, 0xe2, 0x67, 0x0b, 0x19, 0x8b, 0x96,
	0xae, 0xc0, 0x20, 0x07, 0xb6, 0xe2, 0x3b, 0xec, 0xf0, 0xe3, 0x95, 0x63, 0xe1, 0x45, 0x71, 0x49,
	0xd9, 0x58, 0xbc, 0xc0, 0xa0, 0x11, 0x6c, 0x27, 0x97, 0xd7, 0xd1, 0x92, 0xaa, 0x71, 0x42, 0xf1,
	0x78, 0x59, 0xdd, 0x38, 0x43, 0x60, 0xd0, 0xb7, 0x90, 0x8b, 0xed, 0xad, 0xbc, 0x18, 0x7c, 0xa5,
	0x88, 0x93, 0xaf, 0x14, 0x11, 0x7b, 0x5f, 0x29, 0xc5, 0xc3, 0x25, 0xd9, 0xa3, 0x69, 0x04, 0xe6,
	0x98, 0x45, 0x36, 0xe4, 0x62, 0xbb, 0xe7, 0xc5, 0xc7, 0xcf, 0x14, 0x8d, 0x5e, 0x5a, 0x32, 0x1a,
	0x2e, 0x30, 0xde, 0xe0, 0xa4, 0x6c, 0x96, 0x25, 0x83, 0x93, 0x64, 0x2c, 0x1d, 0x9c, 0x24, 0x45,
	0x60, 0x4e, 0xdf, 0xde, 0xde, 0xf1, 0xcc, 0xfb, 0x3b, 0x9e, 0xf9, 0x70, 0xc7, 0xb3, 0x3f, 0x8e,
	0x79, 0xf6, 0x97, 0x31, 0xcf, 0xfe, 0x36, 0xe6, 0xd9, 0xdb, 0x31, 0xcf, 0xfe, 0x39, 0xe6, 0xd9,
	0xbf, 0xc6, 0x3c, 0xf3, 0x61, 0xcc, 0xb3, 0x3f, 0xdd, 0xf3, 0xcc, 0xed, 0x3d, 0xcf, 0xbc, 0xbf,
	0xe7, 0x19, 0xf8, 0xa4, 0x63, 0xf7, 0xc5, 0xae, 0x49, 0xdf, 0x0c, 0xdb, 0xe2, 0x1b, 0xd3, 0xb1,
	0xfb, 0x86, 0xd9, 0xbb, 0x09, 0xcb, 0x1f, 0xf6, 0xcc, 0xf6, 0x69, 0xea, 0x13, 0xf9, 0x66, 0x7d,
	0xda, 0x60, 0x3b, 0xeb, 0x5f, 0xd4, 0xe7, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x38, 0x40,
	0x73, 0x92, 0x0a, 0x00, 0x00,
}

func (x EnumTransactionType) String() string {
	s, ok := EnumTransactionType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Instructions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Instructions)
	if !ok {
		that2, ok := that.(Instructions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Fee != that1.Fee {
		return false
	}
	if this.MaxFee != that1.MaxFee {
		return false
	}
	if this.MaxLedgerVersion != that1.MaxLedgerVersion {
		return false
	}
	if this.MaxLedgerVersionOffset != that1.MaxLedgerVersionOffset {
		return false
	}
	if this.Sequence != that1.Sequence {
		return false
	}
	if this.SignersCount != that1.SignersCount {
		return false
	}
	return true
}
func (this *RequestPrepareTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestPrepareTransaction)
	if !ok {
		that2, ok := that.(RequestPrepareTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxType != that1.TxType {
		return false
	}
	if this.SenderAccount != that1.SenderAccount {
		return false
	}
	if this.Amount != that1.Amount {
		return false
	}
	if this.ReceiverAccount != that1.ReceiverAccount {
		return false
	}
	if !this.Instructions.Equal(that1.Instructions) {
		return false
	}
	return true
}
func (this *ResponsePrepareTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponsePrepareTransaction)
	if !ok {
		that2, ok := that.(ResponsePrepareTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxJSON != that1.TxJSON {
		return false
	}
	if !this.Instructions.Equal(that1.Instructions) {
		return false
	}
	return true
}
func (this *RequestSignTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestSignTransaction)
	if !ok {
		that2, ok := that.(RequestSignTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxJSON != that1.TxJSON {
		return false
	}
	if this.Secret != that1.Secret {
		return false
	}
	return true
}
func (this *ResponseSignTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseSignTransaction)
	if !ok {
		that2, ok := that.(ResponseSignTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxID != that1.TxID {
		return false
	}
	if this.TxBlob != that1.TxBlob {
		return false
	}
	return true
}
func (this *RequestSubmitTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestSubmitTransaction)
	if !ok {
		that2, ok := that.(RequestSubmitTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxBlob != that1.TxBlob {
		return false
	}
	return true
}
func (this *ResponseSubmitTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseSubmitTransaction)
	if !ok {
		that2, ok := that.(ResponseSubmitTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ResultJSONString != that1.ResultJSONString {
		return false
	}
	if this.EarliestLedgerVersion != that1.EarliestLedgerVersion {
		return false
	}
	return true
}
func (this *ResponseWaitValidation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseWaitValidation)
	if !ok {
		that2, ok := that.(ResponseWaitValidation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LedgerVersion != that1.LedgerVersion {
		return false
	}
	return true
}
func (this *RequestGetTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestGetTransaction)
	if !ok {
		that2, ok := that.(RequestGetTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxID != that1.TxID {
		return false
	}
	if this.MinLedgerVersion != that1.MinLedgerVersion {
		return false
	}
	return true
}
func (this *ResponseGetTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseGetTransaction)
	if !ok {
		that2, ok := that.(ResponseGetTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ResultJSONString != that1.ResultJSONString {
		return false
	}
	return true
}
func (this *RequestCombineTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RequestCombineTransaction)
	if !ok {
		that2, ok := that.(RequestCombineTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.SignedTransactions) != len(that1.SignedTransactions) {
		return false
	}
	for i := range this.SignedTransactions {
		if this.SignedTransactions[i] != that1.SignedTransactions[i] {
			return false
		}
	}
	return true
}
func (this *ResponseCombineTransaction) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResponseCombineTransaction)
	if !ok {
		that2, ok := that.(ResponseCombineTransaction)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SignedTransaction != that1.SignedTransaction {
		return false
	}
	if this.TxID != that1.TxID {
		return false
	}
	return true
}
func (this *Instructions) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&rippleapi.Instructions{")
	s = append(s, "Fee: "+fmt.Sprintf("%#v", this.Fee)+",\n")
	s = append(s, "MaxFee: "+fmt.Sprintf("%#v", this.MaxFee)+",\n")
	s = append(s, "MaxLedgerVersion: "+fmt.Sprintf("%#v", this.MaxLedgerVersion)+",\n")
	s = append(s, "MaxLedgerVersionOffset: "+fmt.Sprintf("%#v", this.MaxLedgerVersionOffset)+",\n")
	s = append(s, "Sequence: "+fmt.Sprintf("%#v", this.Sequence)+",\n")
	s = append(s, "SignersCount: "+fmt.Sprintf("%#v", this.SignersCount)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestPrepareTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&rippleapi.RequestPrepareTransaction{")
	s = append(s, "TxType: "+fmt.Sprintf("%#v", this.TxType)+",\n")
	s = append(s, "SenderAccount: "+fmt.Sprintf("%#v", this.SenderAccount)+",\n")
	s = append(s, "Amount: "+fmt.Sprintf("%#v", this.Amount)+",\n")
	s = append(s, "ReceiverAccount: "+fmt.Sprintf("%#v", this.ReceiverAccount)+",\n")
	if this.Instructions != nil {
		s = append(s, "Instructions: "+fmt.Sprintf("%#v", this.Instructions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponsePrepareTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.ResponsePrepareTransaction{")
	s = append(s, "TxJSON: "+fmt.Sprintf("%#v", this.TxJSON)+",\n")
	if this.Instructions != nil {
		s = append(s, "Instructions: "+fmt.Sprintf("%#v", this.Instructions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestSignTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.RequestSignTransaction{")
	s = append(s, "TxJSON: "+fmt.Sprintf("%#v", this.TxJSON)+",\n")
	s = append(s, "Secret: "+fmt.Sprintf("%#v", this.Secret)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseSignTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.ResponseSignTransaction{")
	s = append(s, "TxID: "+fmt.Sprintf("%#v", this.TxID)+",\n")
	s = append(s, "TxBlob: "+fmt.Sprintf("%#v", this.TxBlob)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestSubmitTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&rippleapi.RequestSubmitTransaction{")
	s = append(s, "TxBlob: "+fmt.Sprintf("%#v", this.TxBlob)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseSubmitTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.ResponseSubmitTransaction{")
	s = append(s, "ResultJSONString: "+fmt.Sprintf("%#v", this.ResultJSONString)+",\n")
	s = append(s, "EarliestLedgerVersion: "+fmt.Sprintf("%#v", this.EarliestLedgerVersion)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseWaitValidation) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&rippleapi.ResponseWaitValidation{")
	s = append(s, "LedgerVersion: "+fmt.Sprintf("%#v", this.LedgerVersion)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestGetTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.RequestGetTransaction{")
	s = append(s, "TxID: "+fmt.Sprintf("%#v", this.TxID)+",\n")
	s = append(s, "MinLedgerVersion: "+fmt.Sprintf("%#v", this.MinLedgerVersion)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseGetTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&rippleapi.ResponseGetTransaction{")
	s = append(s, "ResultJSONString: "+fmt.Sprintf("%#v", this.ResultJSONString)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RequestCombineTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&rippleapi.RequestCombineTransaction{")
	s = append(s, "SignedTransactions: "+fmt.Sprintf("%#v", this.SignedTransactions)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ResponseCombineTransaction) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&rippleapi.ResponseCombineTransaction{")
	s = append(s, "SignedTransaction: "+fmt.Sprintf("%#v", this.SignedTransaction)+",\n")
	s = append(s, "TxID: "+fmt.Sprintf("%#v", this.TxID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTransaction(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Instructions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Instructions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Instructions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignersCount != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.SignersCount))
		i--
		dAtA[i] = 0x30
	}
	if m.Sequence != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxLedgerVersionOffset != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.MaxLedgerVersionOffset))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxLedgerVersion != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.MaxLedgerVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MaxFee) > 0 {
		i -= len(m.MaxFee)
		copy(dAtA[i:], m.MaxFee)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.MaxFee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestPrepareTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestPrepareTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestPrepareTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Instructions != nil {
		{
			size, err := m.Instructions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTransaction(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReceiverAccount) > 0 {
		i -= len(m.ReceiverAccount)
		copy(dAtA[i:], m.ReceiverAccount)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.ReceiverAccount)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Amount))))
		i--
		dAtA[i] = 0x19
	}
	if len(m.SenderAccount) > 0 {
		i -= len(m.SenderAccount)
		copy(dAtA[i:], m.SenderAccount)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.SenderAccount)))
		i--
		dAtA[i] = 0x12
	}
	if m.TxType != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.TxType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ResponsePrepareTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponsePrepareTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponsePrepareTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Instructions != nil {
		{
			size, err := m.Instructions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTransaction(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxJSON) > 0 {
		i -= len(m.TxJSON)
		copy(dAtA[i:], m.TxJSON)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxJSON)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestSignTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestSignTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestSignTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Secret) > 0 {
		i -= len(m.Secret)
		copy(dAtA[i:], m.Secret)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.Secret)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxJSON) > 0 {
		i -= len(m.TxJSON)
		copy(dAtA[i:], m.TxJSON)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxJSON)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResponseSignTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseSignTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseSignTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxBlob) > 0 {
		i -= len(m.TxBlob)
		copy(dAtA[i:], m.TxBlob)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxBlob)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxID) > 0 {
		i -= len(m.TxID)
		copy(dAtA[i:], m.TxID)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestSubmitTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestSubmitTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestSubmitTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxBlob) > 0 {
		i -= len(m.TxBlob)
		copy(dAtA[i:], m.TxBlob)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxBlob)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResponseSubmitTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseSubmitTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseSubmitTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EarliestLedgerVersion != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.EarliestLedgerVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ResultJSONString) > 0 {
		i -= len(m.ResultJSONString)
		copy(dAtA[i:], m.ResultJSONString)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.ResultJSONString)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResponseWaitValidation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseWaitValidation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseWaitValidation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LedgerVersion != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.LedgerVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RequestGetTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestGetTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestGetTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinLedgerVersion != 0 {
		i = encodeVarintTransaction(dAtA, i, uint64(m.MinLedgerVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxID) > 0 {
		i -= len(m.TxID)
		copy(dAtA[i:], m.TxID)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResponseGetTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseGetTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseGetTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResultJSONString) > 0 {
		i -= len(m.ResultJSONString)
		copy(dAtA[i:], m.ResultJSONString)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.ResultJSONString)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RequestCombineTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestCombineTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestCombineTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignedTransactions) > 0 {
		for iNdEx := len(m.SignedTransactions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SignedTransactions[iNdEx])
			copy(dAtA[i:], m.SignedTransactions[iNdEx])
			i = encodeVarintTransaction(dAtA, i, uint64(len(m.SignedTransactions[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ResponseCombineTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResponseCombineTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResponseCombineTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxID) > 0 {
		i -= len(m.TxID)
		copy(dAtA[i:], m.TxID)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.TxID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SignedTransaction) > 0 {
		i -= len(m.SignedTransaction)
		copy(dAtA[i:], m.SignedTransaction)
		i = encodeVarintTransaction(dAtA, i, uint64(len(m.SignedTransaction)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Instructions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.MaxFee)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.MaxLedgerVersion != 0 {
		n += 1 + sovTransaction(uint64(m.MaxLedgerVersion))
	}
	if m.MaxLedgerVersionOffset != 0 {
		n += 1 + sovTransaction(uint64(m.MaxLedgerVersionOffset))
	}
	if m.Sequence != 0 {
		n += 1 + sovTransaction(uint64(m.Sequence))
	}
	if m.SignersCount != 0 {
		n += 1 + sovTransaction(uint64(m.SignersCount))
	}
	return n
}

func (m *RequestPrepareTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxType != 0 {
		n += 1 + sovTransaction(uint64(m.TxType))
	}
	l = len(m.SenderAccount)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.Amount != 0 {
		n += 9
	}
	l = len(m.ReceiverAccount)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.Instructions != nil {
		l = m.Instructions.Size()
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func (m *ResponsePrepareTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxJSON)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.Instructions != nil {
		l = m.Instructions.Size()
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func (m *RequestSignTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxJSON)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.Secret)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func (m *ResponseSignTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxID)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.TxBlob)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func (m *RequestSubmitTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxBlob)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func (m *ResponseSubmitTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ResultJSONString)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.EarliestLedgerVersion != 0 {
		n += 1 + sovTransaction(uint64(m.EarliestLedgerVersion))
	}
	return n
}

func (m *ResponseWaitValidation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LedgerVersion != 0 {
		n += 1 + sovTransaction(uint64(m.LedgerVersion))
	}
	return n
}

func (m *RequestGetTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxID)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	if m.MinLedgerVersion != 0 {
		n += 1 + sovTransaction(uint64(m.MinLedgerVersion))
	}
	return n
}

func (m *ResponseGetTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ResultJSONString)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func (m *RequestCombineTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SignedTransactions) > 0 {
		for _, s := range m.SignedTransactions {
			l = len(s)
			n += 1 + l + sovTransaction(uint64(l))
		}
	}
	return n
}

func (m *ResponseCombineTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SignedTransaction)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	l = len(m.TxID)
	if l > 0 {
		n += 1 + l + sovTransaction(uint64(l))
	}
	return n
}

func sovTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTransaction(x uint64) (n int) {
	return sovTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Instructions) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Instructions{`,
		`Fee:` + fmt.Sprintf("%v", this.Fee) + `,`,
		`MaxFee:` + fmt.Sprintf("%v", this.MaxFee) + `,`,
		`MaxLedgerVersion:` + fmt.Sprintf("%v", this.MaxLedgerVersion) + `,`,
		`MaxLedgerVersionOffset:` + fmt.Sprintf("%v", this.MaxLedgerVersionOffset) + `,`,
		`Sequence:` + fmt.Sprintf("%v", this.Sequence) + `,`,
		`SignersCount:` + fmt.Sprintf("%v", this.SignersCount) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestPrepareTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestPrepareTransaction{`,
		`TxType:` + fmt.Sprintf("%v", this.TxType) + `,`,
		`SenderAccount:` + fmt.Sprintf("%v", this.SenderAccount) + `,`,
		`Amount:` + fmt.Sprintf("%v", this.Amount) + `,`,
		`ReceiverAccount:` + fmt.Sprintf("%v", this.ReceiverAccount) + `,`,
		`Instructions:` + strings.Replace(this.Instructions.String(), "Instructions", "Instructions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponsePrepareTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponsePrepareTransaction{`,
		`TxJSON:` + fmt.Sprintf("%v", this.TxJSON) + `,`,
		`Instructions:` + strings.Replace(this.Instructions.String(), "Instructions", "Instructions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestSignTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestSignTransaction{`,
		`TxJSON:` + fmt.Sprintf("%v", this.TxJSON) + `,`,
		`Secret:` + fmt.Sprintf("%v", this.Secret) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseSignTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponseSignTransaction{`,
		`TxID:` + fmt.Sprintf("%v", this.TxID) + `,`,
		`TxBlob:` + fmt.Sprintf("%v", this.TxBlob) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestSubmitTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestSubmitTransaction{`,
		`TxBlob:` + fmt.Sprintf("%v", this.TxBlob) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseSubmitTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponseSubmitTransaction{`,
		`ResultJSONString:` + fmt.Sprintf("%v", this.ResultJSONString) + `,`,
		`EarliestLedgerVersion:` + fmt.Sprintf("%v", this.EarliestLedgerVersion) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseWaitValidation) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponseWaitValidation{`,
		`LedgerVersion:` + fmt.Sprintf("%v", this.LedgerVersion) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestGetTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestGetTransaction{`,
		`TxID:` + fmt.Sprintf("%v", this.TxID) + `,`,
		`MinLedgerVersion:` + fmt.Sprintf("%v", this.MinLedgerVersion) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseGetTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponseGetTransaction{`,
		`ResultJSONString:` + fmt.Sprintf("%v", this.ResultJSONString) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RequestCombineTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RequestCombineTransaction{`,
		`SignedTransactions:` + fmt.Sprintf("%v", this.SignedTransactions) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ResponseCombineTransaction) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ResponseCombineTransaction{`,
		`SignedTransaction:` + fmt.Sprintf("%v", this.SignedTransaction) + `,`,
		`TxID:` + fmt.Sprintf("%v", this.TxID) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTransaction(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Instructions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Instructions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Instructions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLedgerVersion", wireType)
			}
			m.MaxLedgerVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLedgerVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLedgerVersionOffset", wireType)
			}
			m.MaxLedgerVersionOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLedgerVersionOffset |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignersCount", wireType)
			}
			m.SignersCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignersCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestPrepareTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestPrepareTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestPrepareTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxType", wireType)
			}
			m.TxType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxType |= EnumTransactionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Amount = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instructions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Instructions == nil {
				m.Instructions = &Instructions{}
			}
			if err := m.Instructions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponsePrepareTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponsePrepareTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponsePrepareTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxJSON", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxJSON = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instructions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Instructions == nil {
				m.Instructions = &Instructions{}
			}
			if err := m.Instructions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestSignTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestSignTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestSignTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxJSON", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxJSON = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secret", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Secret = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseSignTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseSignTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseSignTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBlob", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxBlob = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestSubmitTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestSubmitTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestSubmitTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBlob", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxBlob = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseSubmitTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseSubmitTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseSubmitTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultJSONString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultJSONString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarliestLedgerVersion", wireType)
			}
			m.EarliestLedgerVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EarliestLedgerVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseWaitValidation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseWaitValidation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseWaitValidation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LedgerVersion", wireType)
			}
			m.LedgerVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LedgerVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestGetTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestGetTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestGetTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLedgerVersion", wireType)
			}
			m.MinLedgerVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLedgerVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseGetTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseGetTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseGetTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultJSONString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultJSONString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestCombineTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestCombineTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestCombineTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedTransactions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedTransactions = append(m.SignedTransactions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResponseCombineTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResponseCombineTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResponseCombineTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedTransaction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedTransaction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTransaction = fmt.Errorf("proto: unexpected end of group")
)
